[project]
name = "scarce2"
version = "1.0.0"
requires-python = ">= 3.10"
dependencies = [
    "fipy",
    "gmsh",
    "matplotlib",
    "numpy",
    "scipy"
]

[build-system]
requires = ["setuptools"]